import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const htmlUrl = new URL("./public/index.html", import.meta.url);
const scriptUrl = new URL("./public/app.js", import.meta.url);
const mascotUrl = new URL("./public/assets/cbu-sleeping-owl-v2.png", import.meta.url);
const html = readFileSync(htmlUrl, "utf8");
const script = readFileSync(scriptUrl, "utf8");
const mascot = readFileSync(mascotUrl);

assert.match(html, /<meta name="viewport" content="width=device-width, initial-scale=1"/);
assert.match(html, /<meta name="theme-color" content="#ffffff"/);
assert.match(html, /<form id="login-form">[\s\S]*autocomplete="username"[\s\S]*autocomplete="current-password"/);
assert.match(html, /class="club-mark"[\s\S]*외박신청을 더 간편하게[\s\S]*로그인하고 시작하기/);
assert.equal(html.match(/src="\/assets\/cbu-sleeping-owl-v2\.png"/g)?.length, 2);
assert.match(html, /<header class="app-header">[\s\S]*class="club-mark"[\s\S]*외박신청<small>by CBU<\/small>/);
assert.doesNotMatch(html, /brand-mark|<span class="brand-mark">T<\/span>/);
assert.equal(mascot.subarray(0, 8).toString("hex"), "89504e470d0a1a0a");
assert.match(html, /<strong>외박신청<\/strong><small>by CBU<\/small>/);
assert.match(html, /.login-brand strong \{ font-size: 32px; font-weight: 600; letter-spacing: -\.04em; \}/);
assert.match(html, /<label for="student-id">포탈 아이디<\/label>/);
assert.match(html, /class="club-link" href="https:\/\/www\.instagram\.com\/tukorea_cbu\/"[\s\S]*한국공학대 개발동아리 CBU[\s\S]*class="external-arrow"[\s\S]*↗/);
assert.equal(html.match(/href="https:\/\/www\.instagram\.com\/tukorea_cbu\/"/g)?.length, 2);
assert.doesNotMatch(html, /\.club-link \{[^}]*background:/);
assert.doesNotMatch(html, /날짜만 고르면 신청은 자동으로|비밀번호는 저장하지 않아요|학교 로그인에만 사용해요|씨부엉이 만들었어요|한국공학대학교 개발동아리/);
assert.doesNotMatch(html, /TUK DORM|외박신청 로그인/);
assert.match(html, /id="calendar-grid" role="grid"/);
assert.match(html, /31일 이내 선택 가능/);
assert.match(html, /\.day\.is-selected:disabled \{ opacity: 1; \}/);
assert.doesNotMatch(html, /오늘부터 31일 안의 날짜를 선택하세요/);
assert.match(html, /<p class="control-copy">외박할 날짜를 선택하세요\.<\/p>/);
assert.match(html, /오늘 포함 7일[\s\S]*오늘 포함 14일[\s\S]*한 달 단위 최대 기간/);
assert.match(html, /<strong>매일<\/strong>[\s\S]*<strong>평일<\/strong>[\s\S]*<strong>주말<\/strong>[\s\S]*<strong>요일 지정<\/strong>/);
assert.match(html, /<legend>어떤 날을<\/legend>[\s\S]*<legend>기간<\/legend>/);
assert.match(html, /\.pattern-options \{ grid-template-columns: repeat\(2,[\s\S]*\.range-options \{ grid-template-columns: repeat\(3,/);
assert.match(html, /id="pattern-help"[\s\S]*금요일부터 일요일까지 선택합니다/);
assert.match(html, /id="mode-auto"[^>]*checked/);
assert.doesNotMatch(html, /id="mode-manual"[^>]*checked/);
assert.match(html, /@media \(max-width: 760px\)[\s\S]*\.submit-bar \{ position: fixed/);
assert.match(html, /\.control-panel \{ order: 1; \}[\s\S]*\.calendar-panel \{ order: 2; \}/);
assert.match(html, /\.calendar-column \{ display: contents; \}[\s\S]*\.club-panel \{ order: 3; \}/);
assert.match(html, /class="calendar-column"[\s\S]*class="panel calendar-panel"[\s\S]*class="panel club-panel"[\s\S]*class="panel control-panel"/);
assert.match(html, /선택한 날[\s\S]*이미 신청한 날[\s\S]*공휴일[\s\S]*data-result="saved" hidden[\s\S]*data-result="unknown" hidden[\s\S]*data-result="exists overlap not_attempted" hidden/);
assert.match(html, /#login-status\[data-kind="error"\]/);
assert.match(html, /<dialog id="service-dialog"[\s\S]*id="dialog-title"[\s\S]*id="dialog-message"[\s\S]*id="dialog-confirm"/);
assert.match(html, /\.dialog-actions:has\(#dialog-confirm\[hidden\]\) \{ display: none; \}/);
assert.match(html, /id="reconcile-job"[\s\S]*자동 선택[\s\S]*달력 직접 선택/);
assert.match(html, /id="holiday-meta"/);
assert.doesNotMatch(html, /공휴일을 제외한 월요일부터 금요일까지/);
assert.doesNotMatch(html, /최근 신청 결과|history-list|history-item/);
assert.doesNotMatch(html, /저장된 계정 다시 연결|계정 연결|학기 퇴관|6개월 퇴관|12개월 퇴관|schedule-meta/);

for (const endpoint of ["/api/login", "/api/applications", "/api/batch/history", "/api/batch/preview", "/api/batch/apply", "/api/batch/reconcile"]) {
  assert.ok(script.includes(endpoint), `${endpoint} UI flow missing`);
}
assert.match(script, /state\.activeJob = job;[\s\S]*renderCalendar/);
assert.doesNotMatch(script, /renderHistory|historyDate|historyTime|summarizeJob/);
assert.match(script, /status-saved|`status-\$\{mark\}`/);
assert.match(script, /const body = \{ dates \}/);
assert.match(script, /pattern === "weekends"[\s\S]*day === 5/);
assert.match(script, /pattern === "weekdays"[\s\S]*return day >= 1 && day <= 5/);
assert.doesNotMatch(script, /pattern === "weekdays"[^\n]*holidayFor/);
assert.match(script, /addDays\(state\.today, state\.maxSelectionDays - 1\)/);
assert.match(script, /dates\.length === 1 \? `\$\{formatDate\(dates\[0\]\)\} 1일 선택`/);
assert.match(script, /\$\{formatDate\(dates\[0\]\)\}~\$\{formatDate\(dates\.at\(-1\)\)\} 중 \$\{dates\.length\}일 선택/);
assert.match(script, /preview\.periods\.map\([\s\S]*dateSummary/);
assert.match(script, /title: "이 날짜로 신청할까요\?"[\s\S]*총 \$\{preview\.dates\.length\}일/);
assert.doesNotMatch(script, /한 기간은 최대 7박 8일이며 기존 신청일은 제외됩니다/);
assert.match(script, /function moveMonth\(offset\)[\s\S]*if \(month < state\.today\.slice\(0, 7\)\) return/);
assert.doesNotMatch(script, /month > maxSelectableDate\(\)\.slice\(0, 7\)/);
assert.match(script, /prevMonthButton\.disabled = viewMonth === state\.today\.slice\(0, 7\)/);
assert.match(script, /nextMonthButton\.disabled = false/);
assert.match(script, /if \(!loadError\) show\(""\)/);
assert.doesNotMatch(script, /학교 신청내역을 새로 불러왔습니다/);
assert.doesNotMatch(html + script, /학교 신청내역/);
assert.doesNotMatch(html + script, /·/);
assert.doesNotMatch(script, /window\.confirm/);
assert.match(script, /function openDialog\([\s\S]*serviceDialog\.showModal\(\)/);
assert.match(script, /applicationSubmitting \? "신청 중…"/);
assert.match(script, /setTimeout\(showProgressDialog, 2000\)/);
assert.match(script, /외박신청을 처리하고 있어요[\s\S]*이 화면을 닫지 마세요\./);
assert.match(script, /closeProgressDialog\(\)[\s\S]*serviceDialog\.dataset\.kind === "progress"/);
assert.match(script, /외박 신청이 완료됐어요/);
assert.match(script, /item\.status === "saved"[\s\S]*dateSummary[\s\S]*총 \$\{savedDays\}일/);
assert.doesNotMatch(script, /개 기간 신청 완료/);
assert.match(script, /showLogin\(error\.message, "error"\)/);
assert.doesNotMatch(script, /pageColor|themeColor/);
assert.doesNotMatch(script, /학교 포탈 계정으로 로그인해 주세요/);
assert.match(script, /로그인 중…" : "로그인하고 시작하기/);
assert.match(script, /patternHelp\.textContent = document\.querySelector\('input\[name="pattern"\]:checked'\)\?\.dataset\.help/);
assert.doesNotMatch(script, /innerHTML|eval\(/);

const syntax = spawnSync(process.execPath, ["--check", fileURLToPath(scriptUrl)], { encoding: "utf8" });
assert.equal(syntax.status, 0, syntax.stderr);

console.log("UI checks passed: single login, 31-day calendar limit, selection patterns, mobile focus, safe DOM rendering");
